-- =============================================================
-- Scavenger Hunt — Supabase Schema
-- Run this in the Supabase SQL editor in order
-- =============================================================


-- =============================================================
-- EXTENSIONS
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- =============================================================
-- ENUMS
-- =============================================================

CREATE TYPE hunt_status AS ENUM ('draft', 'active', 'ended');
CREATE TYPE submission_status AS ENUM ('pending', 'approved', 'rejected', 'failed');
CREATE TYPE ai_suggested_status AS ENUM ('approved', 'rejected');


-- =============================================================
-- TABLES
-- =============================================================

-- hunt
-- Only one row should have status = 'active' at any time.
-- Enforced via a partial unique index below.
CREATE TABLE hunt (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  title       text NOT NULL,
  status      hunt_status NOT NULL DEFAULT 'draft',
  created_at  timestamptz NOT NULL DEFAULT now(),
  started_at  timestamptz,
  ended_at    timestamptz
);

-- Enforce only one active hunt at a time
CREATE UNIQUE INDEX one_active_hunt
  ON hunt (status)
  WHERE status = 'active';


-- clue
-- unlocked_by_clue_id = NULL means the clue is free-hanging (visible from the start).
-- When set, the clue only unlocks after the referenced clue has been submitted by the team.
-- This supports both sequential chains and always-on clues within the same hunt.
CREATE TABLE clue (
  id                   uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  hunt_id              uuid NOT NULL REFERENCES hunt (id) ON DELETE CASCADE,
  unlocked_by_clue_id  uuid REFERENCES clue (id) ON DELETE SET NULL,
  body                 text NOT NULL,
  hint                 text,
  location_name        text,
  points_value         int NOT NULL DEFAULT 10
);

CREATE INDEX clue_hunt_id_idx ON clue (hunt_id);
CREATE INDEX clue_unlocked_by_idx ON clue (unlocked_by_clue_id);


-- team
-- name is nullable — set by the first player to join, changeable anytime after.
-- pin is the team credential, generated by admin and shared manually.
-- No Supabase Auth involved for players — sessions are signed cookies.
CREATE TABLE team (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  hunt_id      uuid NOT NULL REFERENCES hunt (id) ON DELETE CASCADE,
  name         text,                -- null until first player sets it
  pin          text NOT NULL,       -- admin-generated, shared manually
  total_score  int NOT NULL DEFAULT 0,

  UNIQUE (hunt_id, pin)
);

CREATE INDEX team_hunt_id_idx ON team (hunt_id);
CREATE INDEX team_pin_idx ON team (pin);


-- player
-- A new row is created on every join, including rejoins.
-- No uniqueness constraints — player identity within a team is not tracked.
-- team_id + name are display only. player_id is stored in the session cookie.
CREATE TABLE player (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  team_id     uuid NOT NULL REFERENCES team (id) ON DELETE CASCADE,
  name        text NOT NULL,
  joined_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX player_team_id_idx ON player (team_id);


-- submission
CREATE TABLE submission (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  team_id         uuid NOT NULL REFERENCES team (id) ON DELETE CASCADE,
  clue_id         uuid NOT NULL REFERENCES clue (id) ON DELETE CASCADE,
  player_id       uuid NOT NULL REFERENCES player (id) ON DELETE CASCADE,
  photo_url       text NOT NULL,
  submitted_at    timestamptz NOT NULL DEFAULT now(),
  reviewed_at     timestamptz,
  status          submission_status NOT NULL DEFAULT 'pending',
  points_awarded  int NOT NULL DEFAULT 0,

  -- One submission per clue per team, enforced at DB level
  UNIQUE (team_id, clue_id)
);

CREATE INDEX submission_team_id_idx ON submission (team_id);
CREATE INDEX submission_status_idx ON submission (status);


-- announcement
CREATE TABLE announcement (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  hunt_id     uuid NOT NULL REFERENCES hunt (id) ON DELETE CASCADE,
  body        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX announcement_hunt_id_idx ON announcement (hunt_id);


-- ai_review (Phase 5 — table created now, stays empty until then)
CREATE TABLE ai_review (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  submission_id     uuid NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
  model             text NOT NULL,
  confidence        float NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
  suggested_status  ai_suggested_status NOT NULL,
  reviewed_at       timestamptz NOT NULL DEFAULT now(),

  UNIQUE (submission_id)
);


-- =============================================================
-- POSTGRES FUNCTIONS
-- =============================================================

-- join_team
-- Called on player join. Validates PIN against active hunt, creates player row,
-- returns player + team so the API route can issue a session cookie.
-- If team has no name yet, p_team_name must be provided — atomic first-write-wins.
-- If team already has a name, p_team_name is ignored.
CREATE OR REPLACE FUNCTION join_team(
  p_pin         text,
  p_player_name text,
  p_team_name   text DEFAULT NULL
)
RETURNS json AS $$
DECLARE
  v_team    team;
  v_player  player;
  v_team_id uuid;
BEGIN
  -- Find team by PIN in active hunt
  SELECT t.* INTO v_team
  FROM team t
  JOIN hunt h ON h.id = t.hunt_id
  WHERE t.pin = p_pin
    AND h.status IN ('draft', 'active');

  IF v_team IS NULL THEN
    RAISE EXCEPTION 'INVALID_PIN';
  END IF;

  -- Set team name if not yet set (first player, atomic)
  IF v_team.name IS NULL OR v_team.name = '' THEN
    IF p_team_name IS NULL OR p_team_name = '' THEN
      RAISE EXCEPTION 'TEAM_NAME_REQUIRED';
    END IF;

    -- Save ID before UPDATE — a failed RETURNING will NULL out v_team
    v_team_id := v_team.id;

    UPDATE team
    SET name = p_team_name
    WHERE id = v_team_id AND (name IS NULL OR name = '')
    RETURNING * INTO v_team;

    -- If update returned nothing, another player just set the name — refetch
    IF v_team IS NULL THEN
      SELECT * INTO v_team FROM team WHERE id = v_team_id;
    END IF;
  END IF;

  -- Create player row (always insert — rejoins get a new row)
  INSERT INTO player (team_id, name)
  VALUES (v_team.id, p_player_name)
  RETURNING * INTO v_player;

  RETURN json_build_object(
    'player', row_to_json(v_player),
    'team',   row_to_json(v_team)
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- update_team_name
-- Any player can update the team name anytime. Last write wins.
CREATE OR REPLACE FUNCTION update_team_name(
  p_team_id uuid,
  p_name    text
)
RETURNS team AS $$
DECLARE
  v_team team;
BEGIN
  IF p_name IS NULL OR trim(p_name) = '' THEN
    RAISE EXCEPTION 'TEAM_NAME_EMPTY';
  END IF;

  UPDATE team
  SET name = trim(p_name)
  WHERE id = p_team_id
  RETURNING * INTO v_team;

  RETURN v_team;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- submit_clue
-- Inserts submission. Unique constraint on (team_id, clue_id) blocks duplicates.
-- Clue unlocking is derived client-side: a clue becomes visible when the clue it
-- references in unlocked_by_clue_id has been submitted by the same team.
CREATE OR REPLACE FUNCTION submit_clue(
  p_team_id   uuid,
  p_player_id uuid,
  p_clue_id   uuid,
  p_photo_url text
)
RETURNS submission AS $$
DECLARE
  v_submission submission;
BEGIN
  INSERT INTO submission (team_id, player_id, clue_id, photo_url, status)
  VALUES (p_team_id, p_player_id, p_clue_id, p_photo_url, 'pending')
  RETURNING * INTO v_submission;

  RETURN v_submission;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- approve_submission
-- Awards points and marks submission approved.
CREATE OR REPLACE FUNCTION approve_submission(
  p_submission_id uuid
)
RETURNS submission AS $$
DECLARE
  v_submission  submission;
  v_points      int;
BEGIN
  SELECT c.points_value INTO v_points
  FROM submission s
  JOIN clue c ON c.id = s.clue_id
  WHERE s.id = p_submission_id;

  UPDATE submission
  SET
    status         = 'approved',
    points_awarded = v_points,
    reviewed_at    = now()
  WHERE id = p_submission_id
  RETURNING * INTO v_submission;

  UPDATE team
  SET total_score = total_score + v_points
  WHERE id = v_submission.team_id;

  RETURN v_submission;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- reject_submission
-- Marks submission as failed. Team has already progressed, no resubmit.
CREATE OR REPLACE FUNCTION reject_submission(
  p_submission_id uuid
)
RETURNS submission AS $$
DECLARE
  v_submission submission;
BEGIN
  UPDATE submission
  SET
    status      = 'failed',
    reviewed_at = now()
  WHERE id = p_submission_id
  RETURNING * INTO v_submission;

  RETURN v_submission;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- start_hunt
-- Flips status to active. Partial unique index blocks if another hunt is active.
CREATE OR REPLACE FUNCTION start_hunt(
  p_hunt_id uuid
)
RETURNS hunt AS $$
DECLARE
  v_hunt hunt;
BEGIN
  UPDATE hunt
  SET
    status     = 'active',
    started_at = now()
  WHERE id = p_hunt_id AND status = 'draft'
  RETURNING * INTO v_hunt;

  IF v_hunt IS NULL THEN
    RAISE EXCEPTION 'HUNT_NOT_FOUND_OR_NOT_DRAFT';
  END IF;

  RETURN v_hunt;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- end_hunt
CREATE OR REPLACE FUNCTION end_hunt(
  p_hunt_id uuid
)
RETURNS hunt AS $$
DECLARE
  v_hunt hunt;
BEGIN
  UPDATE hunt
  SET
    status   = 'ended',
    ended_at = now()
  WHERE id = p_hunt_id AND status = 'active'
  RETURNING * INTO v_hunt;

  IF v_hunt IS NULL THEN
    RAISE EXCEPTION 'HUNT_NOT_FOUND_OR_NOT_ACTIVE';
  END IF;

  RETURN v_hunt;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- generate_pin
-- Generates a unique PIN for a team. Called server-side when admin creates a team.
-- Retries on collision (extremely unlikely but correct).
CREATE OR REPLACE FUNCTION generate_pin(p_hunt_id uuid)
RETURNS text AS $$
DECLARE
  v_chars  text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  v_pin    text;
  v_exists boolean;
BEGIN
  LOOP
    v_pin := '';
    FOR i IN 1..6 LOOP
      v_pin := v_pin || substr(v_chars, floor(random() * length(v_chars) + 1)::int, 1);
    END LOOP;

    SELECT EXISTS (
      SELECT 1 FROM team WHERE hunt_id = p_hunt_id AND pin = v_pin
    ) INTO v_exists;

    EXIT WHEN NOT v_exists;
  END LOOP;

  RETURN v_pin;
END;
$$ LANGUAGE plpgsql;


-- =============================================================
-- ROW LEVEL SECURITY
-- =============================================================

-- Note: players do not use Supabase Auth. Their identity is a signed
-- server-side cookie containing player_id and team_id. All player-facing
-- API routes validate the cookie server-side and use the admin client
-- to query data — RLS is not relied upon for players.
--
-- RLS is enabled as a safety net but all meaningful access control
-- for players happens in Next.js API route middleware.
--
-- The admin uses the service role key which bypasses RLS entirely.

ALTER TABLE hunt         ENABLE ROW LEVEL SECURITY;
ALTER TABLE clue         ENABLE ROW LEVEL SECURITY;
ALTER TABLE team         ENABLE ROW LEVEL SECURITY;
ALTER TABLE player       ENABLE ROW LEVEL SECURITY;
ALTER TABLE submission   ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcement ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_review    ENABLE ROW LEVEL SECURITY;

-- SELECT policies for realtime: the browser client (anon key) must be able to
-- read these tables so Supabase can deliver postgres_changes events to the client.
-- Writes are still fully protected — all mutations go through SECURITY DEFINER
-- functions or the service role (API routes). Reads for a game are non-sensitive.

CREATE POLICY "anon_select" ON team         FOR SELECT TO anon USING (true);
CREATE POLICY "anon_select" ON submission   FOR SELECT TO anon USING (true);
CREATE POLICY "anon_select" ON announcement FOR SELECT TO anon USING (true);


-- =============================================================
-- REALTIME
-- =============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE team;
ALTER PUBLICATION supabase_realtime ADD TABLE submission;
ALTER PUBLICATION supabase_realtime ADD TABLE announcement;


-- =============================================================
-- STORAGE
-- =============================================================

-- Create in Supabase dashboard: Storage > New bucket
--
-- Bucket name:     submission-photos
-- Public:          false
-- File size limit: 2MB (compression targets ~400KB, 2MB gives headroom)
-- Allowed MIME:    image/jpeg
--
-- Storage is accessed via the admin client (service role) from API routes.
-- Players never upload directly to storage from the browser —
-- the API route handles the upload after validating the session cookie.
